# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "beta", "nightly" ]
  pull_request:
    branches: [ "main", "beta", "nightly" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
        activate-environment: true

    - name: Install dependencies
      run: |
        uv sync --dev
    - name: Lint with Ruff
      run: |
        ruff check --output-format=github .
    - name: Run ty
      run: |
        ty check --output-format=concise
    - name: Test with pytest
      run: |
        pytest -v -s
